// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func MemoryPanel() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<h2>Memory Engine</h2><div class=\"grid-2\"><div class=\"panel\"><h3>Cognitive Layers</h3><ul style=\"list-style: none; padding: 0;\"><li style=\"padding: 0.5rem 0; border-bottom: 1px solid var(--border);\"><span style=\"color: var(--primary);\">System</span>: Core Directives</li><li style=\"padding: 0.5rem 0; border-bottom: 1px solid var(--border);\"><span style=\"color: var(--warning);\">Procedural</span>: Persistent Agent Rules</li><li style=\"padding: 0.5rem 0; border-bottom: 1px solid var(--border);\"><span style=\"color: var(--success);\">Long-Term</span>: Semantic Storage (Vector + FTS)</li><li style=\"padding: 0.5rem 0; border-bottom: 1px solid var(--border);\"><span style=\"color: var(--danger);\">Short-Term</span>: Session working graph</li></ul></div><div class=\"panel\"><h3>Engine Status</h3><div class=\"metric-card\" style=\"margin-bottom: 1rem;\"><div class=\"metric-val\">100%</div><div class=\"metric-label\">Strict Tenant Isolation</div></div><p style=\"color: var(--text-dim); font-size: 0.875rem;\">All memory operations require a valid `TenantContext`. Physical DB files are separate per Workspace.</p></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Layout("Memory Engine").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
