// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func RouterPanel() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<h2>LLM Routing & Policies</h2><div class=\"panel\"><h3>Active Providers</h3><table style=\"width: 100%; text-align: left; border-collapse: collapse; margin-top: 1rem;\"><thead><tr style=\"border-bottom: 2px solid var(--border);\"><th style=\"padding: 0.5rem 0;\">Adapter</th><th style=\"padding: 0.5rem 0;\">Status</th><th style=\"padding: 0.5rem 0;\">Role</th></tr></thead> <tbody><tr style=\"border-bottom: 1px solid var(--border);\"><td style=\"padding: 0.5rem 0;\"><code>ollama</code></td><td style=\"padding: 0.5rem 0; color: var(--success);\">Available</td><td style=\"padding: 0.5rem 0;\">Low Latency / Local Privacy</td></tr><tr style=\"border-bottom: 1px solid var(--border);\"><td style=\"padding: 0.5rem 0;\"><code>gemini</code></td><td style=\"padding: 0.5rem 0; color: var(--success);\">Available</td><td style=\"padding: 0.5rem 0;\">Default Reasoning</td></tr><tr style=\"border-bottom: 1px solid var(--border);\"><td style=\"padding: 0.5rem 0;\"><code>claude</code></td><td style=\"padding: 0.5rem 0; color: var(--warning);\">Not Configured</td><td style=\"padding: 0.5rem 0;\">Complex Reasoning</td></tr></tbody></table></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Layout("LLM Router").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
